apiVersion: v1
kind: Secret
metadata:
  name: innodb-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzcw==
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: default
spec:
  ports:
  - port: 3306
    targetPort: mysql
  selector:
    app: mysql-server
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
  namespace: default
spec:
  serviceName: "mysql-server"
  replicas: 3
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      readinessGates:
        - conditionType: "mysql/innodb-ready"
      containers:
      - image: heheh13/mysql-server:1.0.1
        imagePullPolicy: IfNotPresent
        name: mysql-server
        # args: ["--user=root"]
        # args:
        # - sh
        # - "-c"
        # - |
        #   set -ex
        #   [[ $hostname =~ -([0-9]+)$ ]] || exit 1
        #   ordinal=${BASH_REMATCH[1]}
        #   # echo [mysqld] >> /etc/my.cnf
        #   # echo "report_host=mysql-server-$ordinal.mysql-server.demo.svc" >> /etc/my.cnf
        #   # echo "user=root" >> /etc/my.cnf
        #   rhost="mysql-server-$ordinal.mysql-server.$namespace.svc"
        #   /entrypoint.sh mysqld --user=root --report-host=$rhost
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "innodb-secret"
              key: "MYSQL_ROOT_PASSWORD"
        - name: "hostname"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name : "namespace"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi